runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'stumblr'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'Andr3Igu0d4l49'
  INSTANCE_CONNECTION_NAME: 'stumblr:europe-west1:stumblr-database'

beta_settings:
  cloud_sql_instances: 'stumblr:europe-west1:stumblr-database'
